### ISSUE TITLE
Hissing When Headphones Plugged In ?

### ISSUE THREAD

**Issue by TheEugeneKam** [jsassu20/Lenovo-ThinkPad-T450-Mojave#9]
Hey, an interesting issue that seems to have been present from day one for me. When I plugin headphones like beats or apple once i can see in sound settings that the computer detected something plugged in but there is no volume output, just constant his regardless of sound level.

**Comment by Zardinality** [comment]
Hi, I have exactly the same problem as you. For me, the internal amplifier does not work either, but will not produce any of the hisses.
Things I have tried:
Change the layout-id to 12 and 18.
Add `codec-id`, `device-id` and `vendor-id` like said in the `utility/Audio Configurations`. I found out when I add `device-id`, the `layout-id` won't be injected in `boot.log` and when I do it will be injected to `IntelGFX`. When I add the `vendor-id`, the hiss disappears but also not able to detect any device.
Clean all the previous kexts and restore to the original AppleHDA.kext.
Change to the patched ALC3232(the zlib is missing in the build folder, by the way).
Hope it can avoid some trial and error for you. Also, it is appreciated if you found a way to get the sound&audio working and willing to share.

**Comment by jsassu20** [comment]
Gotta use alc-plug-fix in the alc3232 in the audio configuration folder

**Comment by jsassu20** [comment]
Use AppleALC... The modded one I included, the zlib live in the modified kext thats created after running the scripts. Trust me everything thats required is included.

**Comment by Zardinality** [comment]
@jsassu20 Thanks for the info, I will test out the alc-plug-fix right now.
Yes, I use the AppleALC in the `utility/Audio Configurations, copy it to the `kext/system` and run the command to install it to /L/E. About the zlib, it is said in the `patch_hda.sh` that `./tool/zlib` is called, but the directory contains no folder of name `tool`. I checked the t440s repo and they indeed have one tool folder containing `zlib` and `tag`.

**Comment by Zardinality** [comment]
I have tried to install the `alc-plug-fix` and reboot, but still, with alc3232 I am not able to detect any device. Below are the setting and the kext folder I got:
![image](https://user-images.githubusercontent.com/13702822/58729836-48724d80-839f-11e9-92a8-bcb20b099f2b.png)
![image](https://user-images.githubusercontent.com/13702822/58729923-896a6200-839f-11e9-8241-a314ad7944c8.png)
![image](https://user-images.githubusercontent.com/13702822/58730116-0695d700-83a0-11e9-9b77-73e2597099e7.png)
My boot log is as below:
[log](https://pastebin.com/rYbQhX3W)

**Comment by Zardinality** [comment]
I managed to get the audio working, it turns out you are not required to add the layout-id or any ids to the `config.plist`, just follow what it is originally. The important part is to do a fresh clean of original `CLOVER ` folder and remove any audio patch you originally have in both `/Library/Extensions`  and  `/Library/Extensions`. By this time you should already see the internal amplifier working, but the headphone probably still producing hisses. Then install `alc-plug-fix` in the alc3232 in the audio configuration folder, it will fix the headphone issues for you. I am using a T450S.

**Comment by jsassu20** [comment]
AlcPlugFix in the utilities/Audio Configurations/ALC3232/ALC Fix folder needs to be installed to /usr/bin/ run the script thats in that folder by pointing your terminal to the folder and typing "./install.sh" (no quotes) or by pointing the terminal to the folder and dragging and dropping the install.sh file directly in the open terminal window. You can get to the folder in the terminal by typing "cd /ESP/EFI/CLOVER/utilities/Audio\ Configurations/ALC\ Fix/" or by typing cd followed by a space and dropping the ALC Fix folder in the open terminal window. Then restart after you run the script.

**Comment by jsassu20** [comment]
Layout ID is 2 for ALC3232.kext its 28 for AppleALC.kext

**Comment by jsassu20** [comment]
Both files have the same audio configuration, ones just an actual patched AppleHDA.kext (ALC3232) and the AppleALC is a lilu plugin that patches on the fly. I recommend using AppleALC thats included because I modified it to remove the ALC292 codec and it uses ALC3232 codec instead which fixes issues with the microphone not picking up sound on ALC3232 based hardware. But the files i used to modify it came directly from the ALC3232.kext so they both have the exact same audio configuration its just the AppleALC.kext requires lilu, uses layout-id 28 instead of 2, and supports multiple different laptops instead of only Alc3232 based hardware. Don't ever update the AppleALC kext though its not necessary, itll revert back to ALC292 which will work but you'll have mic issues. New updates to AppleALC only add support for new codec configurations it doesn't change anything about the ones that are already present.

**Comment by svobluk** [comment]
in the last version 3.0 I had to add codeccommander to solve the hissing issue, after that all works fine.

**Comment by jianzhao0806** [comment]
> in the last version 3.0 I had to add codeccommander to solve the hissing issue, after that all works fine.

you mean you just add the codeccommander.kext to solve the issue? I will try!

**Comment by igormclven** [comment]
It's interesting, because with the EFI setup that was in tonymac, also from jsassu20 last year something very interesting was happening...
If you connected some headphones, they made hissing noise. If you put the device on standby with the headphones connected and it woke up, the headphones worked great. 
However if you disconnected them you had to do the same, connect them, put the laptop at rest and wake it up. weird.

**Comment by jianzhao0806** [comment]
> It's interesting, because with the EFI setup that was in tonymac, also from jsassu20 last year something very interesting was happening...
> If you connected some headphones, they made hissing noise. If you put the device on standby with the headphones connected and it woke up, the headphones worked great.
> However if you disconnected them you had to do the same, connect them, put the laptop at rest and wake it up. weird.

Yeah, I find this problem, but I don’t know how to solve it. Maybe the invalid audio port causes the problem.

**Comment by Zardinality** [comment]
Did you guys try manually run the `ALCPlugFix` in the terminal when it is hissing?

**Comment by jianzhao0806** [comment]
Yeah, I tried the ALC3232.kext but it didn’t work, even the speaker.

**Comment by Zardinality** [comment]
I suggest deleting all audio related kexts from your `/S/L/E` and `/L/E`, then use `AppleALC.kext` from the repo or do a clean installation. I manage to get the audio working after the above steps and doing `ALCPlugFix`.

**Comment by jianzhao0806** [comment]
What about the config.plist and the ssdt? So can  you upload your clover folder? I will see it. Thank you very much! :-)

**Comment by Zardinality** [comment]
> What about the config.plist and the ssdt? So can you upload your clover folder? I will see it. Thank you very much! :-)

You probably do not need my `ssdt` and `config.plist`, because eventually I follow exact the `config.plist` and `ssdt` provided by the author.

**Comment by jianzhao0806** [comment]
> > What about the config.plist and the ssdt? So can you upload your clover folder? I will see it. Thank you very much! :-)
> 
> You probably do not need my `ssdt` and `config.plist`, because eventually I follow exact the `config.plist` and `ssdt` provided by the author.

Thank you! I will try it again! ^_^

**Comment by rogelin** [comment]
> /usr/bin/
Is there any workaround for Catalina? I have that hissing too, but when I run the fix script it reports '/usr/bin/' as read only.
Thanks.

**Comment by Zardinality** [comment]
@rogelin simple run the following command in your shell, and then you are good to run the fix script:
```
sudo mount -uw /
killall Finder
```

**Comment by rogelin** [comment]
Still no success with hissing problem... 
I have the T450 and I'm using the kexts provided in this repo. I just run both scripts in Audio Conf. folder.

**Comment by Zardinality** [comment]
Can you fix this problem by directly running the `ALCPlugFix` in that directory? The script does nothing but adding this program to the startup task.

**Comment by rogelin** [comment]
> 
> 
> Can you fix this problem by directly running the `ALCPlugFix` in that directory? The script does nothing but adding this program to the startup task.

No. The scripts runs, but the hissing continue. 
I tried using just the provided AppleALC, AppleALC + script, ALC3232, ALC3232 + script, AppleALC and ALC3232. 
I updated to Catalina from Mojave.
I'm thinking of doing  a clean Catalina install to see if the problems go away.

**Comment by jsassu20** [comment]
Headphones are fixed in latest release, without the need for all plug fix. AppleALC.kext now supports audio on t450 natively with layout id 55 its set in the config.plist of the current version (4.0)

**Comment by iceskullpt** [comment]
Installed catalina yesterday on my t450s and I still have the headphone jack problem, it is not fixed completely.. at least for t450s

Thanks so far for the amazing work

**Comment by ilyhan2009** [comment]
t440s.
Updating of Lilu\AppleALC does not fix hissing.

UPD.
AlcPlugFix + AppleALC fixed hissing.

**Comment by gandol** [comment]
> in the last version 3.0 I had to add codeccommander to solve the hissing issue, after that all works fine.

solved with this
